# Generated by Django 5.2.4 on 2025-07-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shiva", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="shivaa",
            new_name="Shiva",
        ),
    ]
